# Paths
data_folder: "data"
raw_folder: "data/raw"
processed_folder: "data/processed"
output_file: "data.parquet"
db_file: "database.db"
prompts_file: "prompts.yaml"

# Model names
model_hf: "deepseek-ai/DeepSeek-V3"
model_openrouter: "deepseek/deepseek-chat"

# Number of tokens per chunk (for processing long articles)
max_tokens: 7000
